### ISSUE TITLE
Combining with Picturefil

### ISSUE THREAD

**Issue by EN-DD** [jbeyerstedt/kirby-plugin-thumbExt#2]
Could this work with Picturefill - http://scottjehl.github.io/picturefill/
I have been using kirby's thumbnail plugin with picturefill which works really well. Being able to automatically create retina images as well as mobile optimised images would be a great solution.

<picture>

```
<source srcset="examples/images/large.jpg, examples/images/extralarge.jpg 2x" media="(min-width: 800px)">
<img srcset="examples/images/small.jpg, examples/images/medium.jpg 2x" alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia">
```

</picture>

**Comment by jbeyerstedt** [comment]
You had something like this before:

``` php
<picture>
<!--[if IE 9]><video style="display: none;"><![endif]-->
<source srcset="<?php echo thumb($image, array('width' => 500, 'quality' => 80), false) ?>" media="(min-width: 501px)">
<source srcset="<?php echo thumb($image, array('width' => 320, 'quality' => 50), false) ?>" media="(max-width: 500px)">
<!--[if IE 9]></video><![endif]-->
<img srcset="<?php echo thumb($image, array('width' => 500,  'quality' => 80), false) ?>" alt="">
</picture>
```

Now I have added an option to get the srcset-string only, so you example changes to:

``` php
<picture>
<!--[if IE 9]><video style="display: none;"><![endif]-->
<source srcset="<?php echo ThumbExt($image, array('width' => 500, 'quality' => 80, 'srcset-only'=>true)) ?>" media="(min-width: 501px)">
<source srcset="<?php echo ThumbExt($image, array('width' => 320, 'quality' => 50, 'srcset-only'=>true)) ?>" media="(max-width: 500px)">
<!--[if IE 9]></video><![endif]-->
<img srcset="<?php echo ThumbExt($image, array('width' => 500,  'quality' => 80, 'srcset-only'=>true)) ?>" alt="">
</picture>
```

so you would get 1x and 2x images. If you want 3x too, simply add the option `'srcset'=>'2x, 3x'` to the options array.

Please see my latest commit and give me some feedback.

**Comment by EN-DD** [comment]
This is great, thanks! I need to do some testing to make sure it's 
working as expected. I'll get back to you soon with some feedback.

Cheers
Ed

Jannik Beyerstedt wrote:

> You had something like this before:
> 
> <picture>
> 
> 
> 
> <source  srcset="<?php echo thumb($image, array('width' =>  500, 'quality' =>  80), false) ?>"  media="(min-width: 501px)">
> <source  srcset="<?php echo thumb($image, array('width' =>  320, 'quality' =>  50), false) ?>"  media="(max-width: 500px)">
> 
> 
> 
> <img  srcset="<?php echo thumb($image, array('width' =>  500,  'quality' =>  80), false) ?>"  alt="">
> </picture>
> 
> Now I have added an option to get the srcset-string only, so you 
> example changes to:
> 
> <picture>
> 
> 
> 
> <source  srcset="<?php echo ThumbExt($image, array('width' =>  500, 'quality' =>  80, 'srcset-only'=>true)) ?>"  media="(min-width: 501px)">
> <source  srcset="<?php echo ThumbExt($image, array('width' =>  320, 'quality' =>  50, 'srcset-only'=>true)) ?>"  media="(max-width: 500px)">
> 
> 
> 
> <img  srcset="<?php echo ThumbExt($image, array('width' =>  500,  'quality' =>  80, 'srcset-only'=>true)) ?>"  alt="">
> </picture>
> 
> so you would get 1x and 2x images. If you want 3x too, simply add the 
> option |'srcset'=>'2x, 3x'| to the options array.
> 
> Please see my latest commit and give me some feedback.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jbeyerstedt/kirby-plugin-thumbExt/issues/2#issuecomment-102014596.

## 

Sent with Postbox http://www.getpostbox.com

**Comment by EN-DD** [comment]
It's working well for the 2x images. However the crop functionality of the original thumbnail plugin isn't working so the image doesn't resize at a smaller screen size. 

'width' => 500, 'crop' => true,

**Comment by jbeyerstedt** [comment]
Could you please post your code here, because I have tested my plugin with the crop attribute and it seems to work just fine.
By the way: It has to work the same as the original thumb class, because i do nothing other that passing the whole options array to the original thumb class. The only thing the thumbExt function (or thumb_srcset class) does is, that it multiplies the width attribute by the density descriptor. Everything else is part of the original class.

Anyway: If you still have problems with this, I´ll try to help you.

**Comment by jbeyerstedt** [comment]
Closing now, because there was no update.
By the way: This plugin is non needed any more with kirby 3. See https://getkirby.com/docs/reference/objects/file/srcset
